# Dependabot configuration for automated dependency updates
# This helps keep dependencies up-to-date with minimal manual effort
version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates monthly to reduce noise
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      # Check weekly for security updates
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Group minor and patch updates to reduce PR count
    groups:
      androidx:
        patterns:
          - "androidx.*"
      compose:
        patterns:
          - "androidx.compose.*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "org.jetbrains.kotlinx.*"
