blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/disk0Dancer/NFC-bumber/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/disk0Dancer/NFC-bumber/tree/main/docs
    about: Check the project documentation
  - name: Security Issue
    url: https://github.com/disk0Dancer/NFC-bumber/security/advisories/new
    about: Report a security vulnerability privately
