name: Android CI

# Trigger only on important branches and PRs to minimize GitHub Actions minutes
on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

# Cancel previous runs if new commits are pushed to save minutes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    # Set timeout to prevent runaway jobs
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Shallow clone for faster checkout
          fetch-depth: 1
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Cache Gradle dependencies for faster builds
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      # Cache Gradle build outputs to speed up subsequent builds
      - name: Cache Gradle build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      # Run linting and testing in parallel jobs would cost more, 
      # so we run them sequentially but fail fast
      
      - name: Run ktlint
        run: ./gradlew ktlintCheck --no-daemon --stacktrace
        continue-on-error: false
      
      - name: Run Detekt
        run: ./gradlew detekt --no-daemon --stacktrace
        continue-on-error: false
      
      - name: Run unit tests
        run: ./gradlew test --no-daemon --stacktrace
      
      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace
      
      # Only upload artifacts on main branch to save storage
      - name: Upload debug APK
        if: github.ref == 'refs/heads/main' && success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7  # Keep artifacts for only 7 days to save storage
      
      # Upload test results only on failure to help debugging
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            app/build/reports/tests/
            app/build/test-results/
          retention-days: 7
      
      # Upload lint reports only on failure
      - name: Upload lint reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            app/build/reports/ktlint/
            app/build/reports/detekt/
          retention-days: 7
