name: PR Checks

# Lightweight checks for pull requests
on:
  pull_request:
    types: [opened, synchronize, reopened]

# Cancel previous runs to save minutes
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  quick-check:
    name: Quick Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission
        run: chmod +x gradlew
      
      # Only run essential checks for PRs
      - name: Check code style
        run: ./gradlew ktlintCheck --no-daemon
      
      - name: Compile check
        run: ./gradlew compileDebugKotlin --no-daemon
      
      - name: Add PR comment
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Quality checks failed. Please review the logs and fix any issues.'
            })
