name: Close Stale Issues

# This workflow helps keep the issue tracker clean and organized
# by automatically closing inactive issues and PRs

on:
  schedule:
    # Run once a week on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:  # Allow manual trigger

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Close stale issues and PRs
        uses: actions/stale@v9
        with:
          # Number of days before marking as stale
          days-before-stale: 60
          # Number of days before closing after marked stale
          days-before-close: 14
          # Labels to apply
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          # Exempt labels - issues with these labels won't be marked stale
          exempt-issue-labels: 'pinned,security,critical,in-progress'
          exempt-pr-labels: 'pinned,security,critical,in-progress'
          # Messages
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed in 14 days if no further activity occurs.
            Thank you for your contributions.
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed in 14 days if no further activity occurs.
            Thank you for your contributions.
          close-issue-message: >
            This issue was automatically closed because it has been inactive for too long.
            If you believe this issue is still relevant, please reopen it or create a new issue
            with updated information.
          close-pr-message: >
            This pull request was automatically closed because it has been inactive for too long.
            If you would like to continue this work, please reopen the PR or create a new one.
          # Only run on issues/PRs with no activity
          operations-per-run: 30
